#
# Module manifest for module 'EsxTopCollect'
#
# Generated by: Luc Dekens
#
# Generated on: 15-12-16
#

@{
  RootModule        = 'EsxTopCollect'
  ModuleVersion     = '1.0'
  GUID              = '8633fc14-d37a-4e65-8c4a-4855c356d6f6'
  Author            = 'Luc Dekens'
  CompanyName       = 'Unknown'
  Copyright         = '(c) 2016 Luc Dekens. All rights reserved.'
  PowerShellVersion = '3.0'
  FunctionsToExport = 'Get-TopStat','Get-TopMetric','Format-TopData'
  CmdletsToExport   = '*'
  }

